AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  COSC473

  Sample SAM Template for COSC473

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  RetrieveCovidDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: retrieve_covid_data
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          SECRET_NAME: arn:aws:secretsmanager:us-east-1:703990240643:secret:Covid_Act_Now/Api_Key-NaB872
          COUNTY_LIST: "s3://bigdata2bucket/county-list.parquet"
          OUTPUT_FILE: "s3://bigdata2bucket/counties.csv"
      Events:
        UpdateData:
          Type: Schedule
          Properties:
            #EventBusName: your-event-bus-name #Uncomment this if your events are not on the 'default' event bus
            Name: UpdateData
            Schedule: 'cron(0 0 * * ? *)'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RetrieveCovidDataFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RetrieveCovidDataFunction.Arn
  RetrieveCovidDataFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RetrieveCovidDataFunctionRole.Arn
